# This is a basic workflow to help you get started with Actions

name: Build Java Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build_java.yml
      - java/Dockerfile.java
      - resources/java/*
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build_java.yml
      - java/Dockerfile.java
      - resources/java/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  IMAGE_OS: "bookworm"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build_core_java:
    strategy:
      matrix:
        java_version: ["21.0.2"]
    runs-on: ubuntu-latest
    env:
      JAVA_VARIANT: open
    steps:
    - uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        file: java/Dockerfile.java
        tags: corpheus91/devcontainers:java-${{matrix.java_version}}-${{env.IMAGE_OS}}
        build-args: |
          VERSION=${{matrix.java_version}}
          BASE=${{env.IMAGE_OS}}
          JAVA_VARIANT=${{env.JAVA_VARIANT}}

  build_variant_dind:
    strategy:
      matrix:
        language_and_version: ["java-21.0.2"]
    env:
      REGISTRY: corpheus91/devcontainers
    runs-on: ubuntu-latest
    needs: [build_core_java]
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: dind/Dockerfile.dind
          tags: corpheus91/devcontainers:${{matrix.language_and_version}}-dind
          build-args: |
            IMAGE=${{env.REGISTRY}}:${{matrix.language_and_version}}-${{env.IMAGE_OS}}     

  build_variant_kubernetes:
    strategy:
      matrix:
        language_and_version: ["java-21.0.2"]
    env:
      REGISTRY: corpheus91/devcontainers
    runs-on: ubuntu-latest
    needs: [build_core_java]
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: kubernetes/Dockerfile.kubernetes
          tags: corpheus91/devcontainers:${{matrix.language_and_version}}-kubernetes
          build-args: |
            IMAGE=${{env.REGISTRY}}:${{matrix.language_and_version}}-${{env.IMAGE_OS}}
