# This is a basic workflow to help you get started with Actions

name: Build Python Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build_python.yml
      - python/Dockerfile.python
      - resources/python/*
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build_python.yml
      - python/Dockerfile.python
      - resources/python/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  IMAGE_OS: "bookworm"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build_core_python:
    strategy:
      matrix:
        python_version: ["3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        file: python/Dockerfile.python
        tags: corpheus91/devcontainers:python-${{matrix.python_version}}-${{env.IMAGE_OS}}
        build-args: |
          VERSION=${{matrix.python_version}}
          BASE=${{env.IMAGE_OS}}

  build_variant_dind:
    strategy:
      matrix:
        language_and_version: [ 
          "python-3.11", 
          "python-3.12",
          "python-3.13"
        ]
    env:
      REGISTRY: corpheus91/devcontainers
    runs-on: ubuntu-latest
    needs: [
      build_core_python
    ]
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: dind/Dockerfile.dind
          tags: corpheus91/devcontainers:${{matrix.language_and_version}}-dind
          build-args: |
            IMAGE=${{env.REGISTRY}}:${{matrix.language_and_version}}-${{env.IMAGE_OS}}
        
  build_variant_kubernetes:
    strategy:
      matrix:
        language_and_version: [
          "python-3.11", 
          "python-3.12",
          "python-3.13"
        ]
    env:
      REGISTRY: corpheus91/devcontainers
    runs-on: ubuntu-latest
    needs: [
      build_core_python
    ]
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: kubernetes/Dockerfile.kubernetes
          tags: corpheus91/devcontainers:${{matrix.language_and_version}}-kubernetes
          build-args: |
            IMAGE=${{env.REGISTRY}}:${{matrix.language_and_version}}-${{env.IMAGE_OS}}
