# This is a basic workflow to help you get started with Actions

name: Build ArgoCD Plugin Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build_argocd_plugin.yml
      - argocd/plugins/Dockerfile.argocd-plugin
      - resources/argocd/plugins/*
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build_argocd_plugin.yml
      - argocd/plugins/Dockerfile.argocd-plugin
      - resources/argocd/plugins/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  IMAGE_OS: "bookworm"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build_argocd_plugin:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        file: argocd/plugins/Dockerfile.argocd-plugin
        tags: corpheus91/argocd-plugin:python-${{matrix.python_version}}-${{env.IMAGE_OS}}
        build-args: |
          VERSION=${{matrix.python_version}}
